import Foundation
import OSLog
import ToolkitCore

public struct TrustedIntelligenceSource: Hashable, Sendable, Identifiable {
    public let id: String
    public let name: String
    public let organization: String
    public let repository: String
    public let branch: String
    public let path: String
    public let licenseName: String
    public let description: String

    public init(id: String, name: String, organization: String, repository: String, branch: String, path: String, licenseName: String, description: String) {
        self.id = id
        self.name = name
        self.organization = organization
        self.repository = repository
        self.branch = branch
        self.path = path
        self.licenseName = licenseName
        self.description = description
    }
}

public enum TrustedIntelligenceUpdater {
    public static let sources: [TrustedIntelligenceSource] = [
        TrustedIntelligenceSource(
            id: "amnesty-pegasus",
            name: "Amnesty Security Lab — Pegasus",
            organization: "Amnesty International Security Lab",
            repository: "AmnestyTech/investigations",
            branch: "master",
            path: "2021-07-18_nso/pegasus.stix2",
            licenseName: "Repository-specific terms; indicators remain external data",
            description: "Published Pegasus investigation indicators from Amnesty International Security Lab."
        ),
        TrustedIntelligenceSource(
            id: "mvt-triangulation",
            name: "MVT Indicators — Operation Triangulation",
            organization: "MVT project contributors",
            repository: "mvt-project/mvt-indicators",
            branch: "main",
            path: "2023-06_01_operation_triangulation/operation_triangulation.stix2",
            licenseName: "Repository-specific terms; indicators remain external data",
            description: "Community-maintained indicators referenced by the MVT project."
        ),
        TrustedIntelligenceSource(
            id: "imazing-kingspawn",
            name: "iMazing IOC — KingsPawn / QuaDream",
            organization: "DigiDNA / iMazing",
            repository: "DigiDNA/iMazing-Indicators-Of-Compromise",
            branch: "main",
            path: "spywares/2023-04-11_KingsPawn-QuaDream/kingspawn.stix2",
            licenseName: "Repository-specific terms; indicators remain external data",
            description: "STIX2 indicators generated by the iMazing team for its published KingsPawn research."
        ),
    ]

    public static func update(_ source: TrustedIntelligenceSource, destinationRoot: URL, maximumBytes: Int, attempts: Int) async throws -> IntelligenceBundle {
        guard destinationRoot.path.hasPrefix("/") else { throw ToolkitError.invalidInput("The threat-intelligence cache path must be absolute.") }
        guard maximumBytes > 0, attempts > 0 else { throw ToolkitError.invalidInput("Threat-intelligence download limits must be positive.") }
        try ensurePrivateDirectoryWithoutSymlink(destinationRoot, label: "threat-intelligence cache")

        let commitURL = try latestCommitURL(source)
        let metadata = try await fetch(commitURL, maximumBytes: 1_000_000, attempts: attempts)
        let payload = try JSONValue.parse(metadata)
        guard let commit = payload.array?.first?.object?["sha"]?.string,
              commit.count == 40,
              commit.allSatisfy(\.isHexDigit) else {
            throw ToolkitError(.protocolViolation, message: "GitHub returned invalid commit metadata for \(source.name).")
        }
        let encodedPath = source.path.split(separator: "/").map { String($0).addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? String($0) }.joined(separator: "/")
        guard let rawURL = URL(string: "https://raw.githubusercontent.com/\(source.repository)/\(commit)/\(encodedPath)") else {
            throw ToolkitError.invalidInput("Could not construct the commit-pinned URL for \(source.name).")
        }
        let content = try await fetch(rawURL, maximumBytes: maximumBytes, attempts: attempts)
        try Task.checkCancellation()

        let sourceDirectory = destinationRoot.appendingPathComponent(source.id, isDirectory: true)
        try ensurePrivateDirectoryWithoutSymlink(sourceDirectory, label: "cached source folder")
        let suffix = URL(fileURLWithPath: source.path).pathExtension.nilIfEmpty ?? "stix2"
        let destination = sourceDirectory.appendingPathComponent("\(commit).\(suffix)")
        if FileManager.default.fileExists(atPath: destination.path) {
            let existing = try Data(contentsOf: destination, options: [.mappedIfSafe])
            guard existing == content else {
                throw ToolkitError(.protocolViolation, message: "Cached intelligence does not match the commit-pinned download.", technicalDetail: destination.path)
            }
        } else {
            try SecureFileIO.writeNewFile(content, to: destination)
        }
        return try ThreatIntelligence.loadLocalFile(
            destination,
            sourceName: source.name,
            organization: source.organization,
            sourceURL: rawURL.absoluteString,
            version: String(commit.prefix(12)),
            commit: commit,
            publishedAt: nil,
            signatureStatus: "not-provided",
            importedAt: ISO8601DateFormatter().string(from: Date()),
            maximumBytes: maximumBytes
        )
    }

    private static func latestCommitURL(_ source: TrustedIntelligenceSource) throws -> URL {
        guard var components = URLComponents(string: "https://api.github.com/repos/\(source.repository)/commits") else {
            throw ToolkitError.invalidInput("Could not construct the GitHub metadata URL for \(source.name).")
        }
        components.queryItems = [
            URLQueryItem(name: "path", value: source.path),
            URLQueryItem(name: "sha", value: source.branch),
            URLQueryItem(name: "per_page", value: "1"),
        ]
        guard let url = components.url else { throw ToolkitError.invalidInput("Could not encode the GitHub metadata URL for \(source.name).") }
        return url
    }

    private static func ensurePrivateDirectoryWithoutSymlink(_ directory: URL, label: String) throws {
        if FileManager.default.fileExists(atPath: directory.path) {
            let values: URLResourceValues
            do {
                values = try directory.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
            } catch {
                throw ToolkitError.fileSystem("Could not inspect the \(label).", path: directory.path, underlying: error)
            }
            guard values.isDirectory == true, values.isSymbolicLink != true else {
                throw ToolkitError.invalidInput("The \(label) must be a real directory, not a symbolic link.")
            }
        }
        try SecureFileIO.createPrivateDirectory(at: directory)
    }

    private static func fetch(_ url: URL, maximumBytes: Int, attempts: Int) async throws -> Data {
        guard url.scheme == "https" else { throw ToolkitError.invalidInput("Threat-intelligence network requests require HTTPS: \(url.absoluteString)") }
        let logger = Logger(subsystem: "io.hideouts.iOSDeveloperToolkit", category: "ThreatIntelligence")
        var lastError: Error?
        for attempt in 1...attempts {
            try Task.checkCancellation()
            do {
                var request = URLRequest(url: url)
                request.timeoutInterval = 20
                request.setValue("application/vnd.github+json, application/json, text/plain", forHTTPHeaderField: "Accept")
                request.setValue("iOS-Developer-Toolkit", forHTTPHeaderField: "User-Agent")
                let (bytes, response) = try await URLSession.shared.bytes(for: request)
                guard let http = response as? HTTPURLResponse else { throw ToolkitError(.protocolViolation, message: "Threat-intelligence server returned a non-HTTP response.", technicalDetail: url.absoluteString) }
                guard (200..<300).contains(http.statusCode) else { throw ToolkitError(.commandFailed, message: "Threat-intelligence request returned HTTP \(http.statusCode).", technicalDetail: url.absoluteString) }
                if response.expectedContentLength > Int64(maximumBytes) {
                    throw ToolkitError(.protocolViolation, message: "Threat-intelligence response exceeds the \(maximumBytes)-byte safety limit.", technicalDetail: url.absoluteString)
                }
                var data = Data()
                data.reserveCapacity(min(maximumBytes, max(0, Int(response.expectedContentLength))))
                for try await byte in bytes {
                    if data.count >= maximumBytes {
                        throw ToolkitError(.protocolViolation, message: "Threat-intelligence response exceeds the \(maximumBytes)-byte safety limit.", technicalDetail: url.absoluteString)
                    }
                    data.append(byte)
                }
                return data
            } catch is CancellationError {
                throw CancellationError()
            } catch {
                lastError = error
                logger.warning("Threat-intelligence request failed url=\(url.absoluteString, privacy: .public) attempt=\(attempt, privacy: .public) attempts=\(attempts, privacy: .public) error=\(String(describing: error), privacy: .private)")
                if attempt < attempts {
                    try await Task.sleep(for: .seconds(attempt))
                }
            }
        }
        guard let lastError else { throw ToolkitError(.commandFailed, message: "Threat-intelligence request failed without an error.", technicalDetail: url.absoluteString) }
        throw ToolkitError(.commandFailed, message: "Threat-intelligence request failed after \(attempts) attempts.", technicalDetail: "\(url.absoluteString)\n\(String(describing: lastError))")
    }
}

extension String {
    fileprivate var nilIfEmpty: String? { isEmpty ? nil : self }
}
